name: Automatic Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - name: Windows Setup Dependency
      if: contains(matrix.config.os, 'windows')
      uses: johnwason/vcpkg-action@v7
      with:
        pkgs: czmq
        triplet: x64-windows-release
        token: ${{ github.token }}
    - name: Linux Setup Dependency
      if: contains(matrix.config.os, 'ubuntu')
      run: sudo apt-get install libczmq-dev
    - name: make all
      run: make all
    - uses: actions/upload-artifact@v4
      with:
        name: universal-builds-linux
        path: |
          universal-pubsub
          universal-sub-pubsub
          universal-xpubxsub
          universal-sub-xpubxsub
          universal-sub-xpubxsub-timeout
