name: Automatic Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - name: Windows Setup Dependency
      if: contains(matrix.config.os, 'windows')
      uses: johnwason/vcpkg-action@v7
      with:
        pkgs: zeromq
        triplet: x64-windows-release
        token: ${{ github.token }}
    - name: Linux Setup Dependency
      if: contains(matrix.config.os, 'ubuntu')
      run: sudo apt-get install libczmq-dev
    - name:  Linux make all
      if: contains(matrix.config.os, 'ubuntu')
      run: make all
    - name: Install NuGet
      if: contains(matrix.config.os,'windows')
      run: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Confirm:$false
    - name: Install Show-Tree
      if: contains(matrix.config.os,'windows')
      run: Install-Module -Name Pscx -AllowClobber -Force -Confirm:$false
    - name: List files
      if: contains(matrix.config.os,'windows')
      run: Show-Tree "${{ github.workspace }}\vcpkg\installed\x64-windows-release\lib\pkgconfig" -depth 10
    - name:  Windows make all
      if: contains(matrix.config.os,'windows')
      run: make LDFLAGS="-L${{ github.workspace }}\vcpkg\installed\x64-windows-release\lib\pkgconfig -Wl,-rpath,${{ github.workspace }}\vcpkg\installed\x64-windows-release\lib\pkgconfig" all
   
    - uses: actions/upload-artifact@v4
      with:
        name: universal-builds-linux
        path: |
          universal-pubsub
          universal-sub-pubsub
          universal-xpubxsub
          universal-sub-xpubxsub
          universal-sub-xpubxsub-timeout
